analysis_variables: &analysis_variables !INC ./analysis_variables.yaml
atm_window_begin: &atm_window_begin !ENV "${ATM_WINDOW_BEGIN}"
model_bkgrds: &model_bkgrds !INC ./soca_backgrounds.yaml
model_state: &model_state !INC ./state_variables.yaml

# ----

cost function:

  cost type: 4D-Var
  window_begin: *atm_window_begin
  window_length: !ENV ${ATM_WINDOW_LENGTH}
  observations: !INC ./soca_observations.yaml
  analysis variables: *analysis_variables
  geometry:
    mom6_input_nml: mom_input.nml
    fields metadata: ./fields_metadata.yaml

  model:
    name: PseudoModel
    tstep: PT1H
    state variables: *model_state
    states: *model_bkgrds

  background:
    read_from_file: 1
    basename: ./INPUT/
    ocn_filename: MOM.res.nc
    ice_filename: 
    date: *atm_window_begin 
    state variables: *model_state
  background error: !INC ./soca_berror.yaml

variational:
  minimizer:
    algorithm: RPCG
  iterations:
  - geometry:
      mom6_input_nml: mom_input.nml
      fields metadata: ./fields_metadata.yaml
    linear model:
      name: Identity
      increment variables: *analysis_variables
      variable change: Identity
      tstep: PT1H
    ninner: !ENV ${NINNER} !!int
    gradient norm reduction: 1e-10
    test: on
    diagnostics:
      departures: ombg
    online diagnostics:
      write increment: true
      increment:
        datadir: Data
        date: *atm_window_begin
        exp: iter1
        type: incr

minimizer:
  algorithm: RPCG

output:
  datadir: Data
  exp: 3dvarfgat_pseudo
  type: an

final:
  diagnostics:
    departures: oman
  increment:
    output:
      datadir: Data
      date: *atm_window_begin
      exp: 3dvarfgat_pseudo
      type: incr
    geometry:
      mom6_input_nml: mom_input.nml
      fields metadata: ./fields_metadata.yaml
