observations: &observations !INC ./soca_observations.yaml
observations2: &observations2 !INC ./soca_observations.yaml


# ----


cost function:

  observations: *observations
  observations2: *observations2
