_: &observations: !INC ./soca_observations.yaml



# ----


cost function:
  cost type: 4D-Var
  #window begin: '{{ATM_WINDOW_BEGIN}}'
  #window length: $(ATM_WINDOW_LENGTH)
  analysis variables: &a_vars  [cicen, hicen, socn, tocn, ssh]
  geometry:
    mom6_input_nml: mom_input.nml
    fields metadata: ./fields_metadata.yaml

  model:
    name: PseudoModel
    tstep: PT1H
    state variables: &model_vars [cicen, hicen, hsnon, socn, tocn, ssh, hocn, uocn, vocn, mld, layer_depth]
    #states: !INC ${BKG_LIST}

  background:
    read_from_file: 1
    basename: ./INPUT/
    ocn_filename: MOM.res.nc
    ice_filename: cice.res.nc
    #date: '{{ATM_WINDOW_BEGIN}}'
    state variables: *model_vars
  #background error: !INC ${SABER_BLOCKS_YAML}

  observations: *observations
