obs space:
  name: !ENV ${OBS_SPACE_NAME}
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${OBS_DATAFILE_IN}
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${OBS_DATAFILE_OUT}
  simulated variables: [sea_ice_area_fraction]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal
