#!/bin/bash --posix

################################################################################
#### UNIX Script Documentation Block
##
## Script name:         JUFS_FETCH_OCEANOBS
##
## Script description:  Launch the UFS workflow ocean observation
##                      collection application.
##
## Author:              Henry R. Winterbottom 
##
## Date:                2022-12-19         
##
## Script history log:  
##
##   2022-12-19: Henry R. Winterbottom -- Original version.
##
## Usage: sh JUFS_FETCH_OCEANOBS
##
##   Imported Shell Variables:
##
##     CYCLEufs:         The respective UFS forecast cycle.
##
##     HOMEufs:          The top-level working directory for all UFS-RNR
##                       applications.
##
##     PREufs:           The full-path to the (supported) platform-dependent
##                       required utilities and/or modules script.
##
##     YAMLufs:          The YAML-formatted configuration file for the
##                       respective UFS experiment.
##
##   Exported Shell Variables:
##
##     UFS_STAGE:        UFS workflow environment variable for respective
##                       task.
##
##     pid:              UNIX system processes identifier.  
##
## Remarks:
##
##   Condition codes:
##
##      0 - no problem encountered
##     >0 - some problem encountered
##
## Attributes:
##
##   Language: POSIX shell
##   Machine: IBM SP
##
################################################################################

set -e

# Load all modules required by utilities referenced by this script.
export UFS_STAGE=1
. ${PREufs}

# Define the run-time environment for the respective UFS-RNR
# application.
export PYTHONPATH="${HOMEufs}/ush"

# Get processor id (pid).
export pid=$$

# Launch the UFS-RNR experiment application.
python ${HOMEufs}/scripts/exufs_fetch.py --yaml_file=${YAMLufs} --cycle=${CYCLEufs} --fetch_opt=ocean_obs

# Collect (any) error information and exit.
export ERR=$?
export err=${ERR}
exit ${err}
