# =========================================================================

# YAML: .github/workflows/unittests.yaml

# Author: Henry R. Winterbottom

# Email: henry.winterbottom@noaa.gov

# This program is free software: you can redistribute it and/or modify
# it under the terms of the respective public license published by the
# Free Software Foundation and included with the repository within
# which this application is contained.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# =========================================================================

# Description
# -----------

#    This file contains a Github actions/workflow to build a Miniconda
#    environment, install the ufs_fetchapp required packages, and run
#    the respective unit-test application. This workflow action is
#    invoked when a Github pull request is opened, a release is
#    published, and at 0000 UTC every day.

# Author(s)
# ---------

#    Henry R. Winterbottom; 04 January 2023

# History
# -------

#    2023-01-04: Henry Winterbottom -- Initial implementation.

#----

# Define the name of the Github actions/workflow.
name: Unit Tests

# Define the Github triggers for which to launch the respective Github
# action/workflow.
on:
  pull_request:
    types: [opened]
    
  release:
    types: [published]

  schedule:
    - cron: "0 0 * * *"
          
jobs:

  # Define the container image.
  build:
    runs-on: ubuntu-latest
    name: Run the ufs_apps unit-tests.
        
    steps:

    # Build the Python environment via Miniconda and install the
    # necessary packages and dependencies.
    - name: Build and install Python dependencies
      run: |
        wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
        sh Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda
        python -m pip install --upgrade pip
        pip install netcdf4
        conda install numpy
        pip install astropy
        pip install bs4
        pip install croniter
        pip install pytest==7.2.0
        pip install pytest-order
        pip install moto
        conda install -c anaconda pyyaml
        conda install -c anaconda boto3

    # Clone the ufs_apps repository branch.
    - name: Checkout ufs_apps.
      uses: actions/checkout@v3
      with:
        path: ufs_apps

    # Clone the ufs_pyutils repository branch.
    - name: Checkout ufs_pyutils.
      uses: actions/checkout@v3
      with:
        repository: HenryWinterbottom-NOAA/ufs_pyutils
        token: ${{ secrets.MY_TOKEN || github.token }}
        path: ufs_pyutils
         
    # Execute the fetch application unit-tests.
    - name: Run ufs_apps package fetch application unit-tests.
      run: |
        echo $GITHUB_WORKSPACE
        echo "LOOKING AT  $GITHUB_WORKSPACE"
        ls $GITHUB_WORKSPACE
        echo "LOOKING AT  $GITHUB_WORKSPACE/ufs_apps"
        ls $GITHUB_WORKSPACE/ufs_apps/
        echo "LOOKING AT  $GITHUB_WORKSPACE/ufs_pyutils"
        ls  $GITHUB_WORKSPACE/ufs_pyutils
        export PYTHONPATH=$GITHUB_WORKSPACE/ufs_pyutils:$GITHUB_WORKSPACE/ufs_apps/ush
        echo "PYTHONPATH" $PYTHONPATH
        echo "LOOKING AT $GITHUB_WORKSPACE/ufs_apps/ush/staging/tests"
        cd $GITHUB_WORKSPACE/ufs_apps/ush/staging/tests
        ls
        #pytest

